services:
  emulator:
    build: .
    ports:
      - '14000:4000'
      - '15002:5002'
      - '15001:5001'
      - '18080:8080'
      - '18085:8085'
      - '19000:9000'
      - '19005:9005'
      - '19099:9099'
      - '19199:9199'
      - '19299:9299'
  resultserver:
    build:
      context: ./integration-tests/server
      dockerfile: Dockerfile-result-server
    ports:
      - '12345:12345'
  embedder-server:
    build:
      context: ./integration-tests/server
      dockerfile: Dockerfile-embedder-server
    ports:
      - '12344:12344'
  typesense-server:
    build:
      context: ./integration-tests/server
      dockerfile: Dockerfile-typesense-server
    ports:
      - '12343:12343'
