services:
  emulator:
    extends:
      file: docker-compose-base.yml
      service: emulator
    volumes:
      - ./functions/src:/app/functions/src
      - ./functions/lib:/app/functions/lib
  resultserver:
    extends:
      file: docker-compose-base.yml
      service: resultserver
  embedder-server:
    extends:
      file: docker-compose-base.yml
      service: embedder-server
  typesense-server:
    extends:
      file: docker-compose-base.yml
      service: typesense-server
