name: Run Tests
on:
  pull_request:
    paths:
      - 'functions/**'
  push:
    branches:
      - main
    paths:
      - 'functions/**'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: sarge1989/checkmate:latest
      - name: Build
        run: docker-compose build

      - name: Run unit tests
        run: docker run checkmate_emulator:latest npm run functions:unittests
      # - name: Run unit tests
      #   run: docker run sarge1989/checkmate:latest npm run functions:unittests
      # - name: Build docker image for testing
      #   run: docker-compose build --no-cache
      # - name: Run unit tests in functions folder
