name: Run Tests
on:
  pull_request:
    paths:
      - 'functions/**'
  push:
    branches:
      - main
    paths:
      - 'functions/**'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm i
        working-directory: functions
      - name: Run unit tests
        run: npm test
        working-directory: functions
